FROM birdsystem/app
MAINTAINER Allan Sun <allan.sun@bricre.com>

RUN APP_ENVIRONMENT=testing

RUN apt-get update && apt-get -yq install --no-install-recommends \
    php7.0-xdebug php7.0-phpdbg\
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# php.ini settings
COPY php.testing.ini /etc/php7/conf.d/zz-settings.ini
COPY php.testing.ini /etc/php/7.0/phpdbg/conf.d/zz-settings.ini

WORKDIR /var/www/back