version: '2'
services:
  maria:
    build:
      context: ./docker/mariadb
    volumes:
      - ./docker/mariadb:/init
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=aeiEJA93Kadki93f
      - MYSQL_USER=send_for_you
      - MYSQL_PASSWORD=BatTrapComfortableFootball
      - MYSQL_DATABASE=send_for_you
    ports:
      - '3308:3306'

  app-development:
    build:
      context: ./docker/app
      dockerfile: Dockerfile.development
    ports:
      - "8300:80"

  app-testing:
    build:
      context: ./docker/app
      dockerfile: Dockerfile.testing

  app-production:
    build:
      context: ./docker/app
      dockerfile: Dockerfile.production