version: '2'
services:
  maria:
    build:
      context: ./docker/mariadb
    volumes:
      - ./docker/mariadb:/init
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - '3306:3306'

  app-development:
    build:
      context: ./docker/app
      dockerfile: Dockerfile.development
    ports:
      - "80:80"

  app-testing:
    build:
      context: ./docker/app
      dockerfile: Dockerfile.testing

  app-production:
    build:
      context: ./docker/app
      dockerfile: Dockerfile.production